# numpy基础 数组和矢量计算
http://python.jobbole.com/87352/

In [1]:
import numpy as np 
 
data=np.array([2,5,6,8,3]) #构造一个简单的数组
 
print(data)

[2 5 6 8 3]


In [2]:
data1=np.array([[2,5,6,8,3],np.arange(5)])  #构建一个二维数组
 
print(data1)

[[2 5 6 8 3]
 [0 1 2 3 4]]


我们也可以通过shape和dtype方法查看数组的维度和数据格式

In [3]:
print(data.shape)
print(data.dtype)
print(data1.shape)
print(data1.dtype)

(5,)
int64
(2, 5)
int64


其他的数组属性方法还有：

array.ndim   数组的维数，一维数组结果为1，二维数组打印结果为2

array.size     数组的元素个数

array.itemsiz   数组每个元素的字节大小

#### NumPy中的基本数据类型

| 名称                | 描述                                              |
|---------------------|---------------------------------------------------|
| bool                | 用一个字节存储的布尔类型（True或False）           |
| inti                | 由所在平台决定其大小的整数（一般为int32或int64）  |
| int8                | 一个字节大小，-128 至 127                         |
| int16               | 整数，-32768 至 32767                             |
| int32               | 整数，-2 ** 31 至 2 ** 32 -1                      |
| int64               | 整数，-2 ** 63 至 2 ** 63 – 1                     |
| uint8               | 无符号整数，0 至 255                              |
| uint16              | 无符号整数，0 至 65535                            |
| uint32              | 无符号整数，0 至 2 ** 32 – 1                      |
| uint64              | 无符号整数，0 至 2 ** 64 – 1                      |
| float16             | 半精度浮点数：16位，正负号1位，指数5位，精度10位  |
| float32             | 单精度浮点数：32位，正负号1位，指数8位，精度23位  |
| float64或float      | 双精度浮点数：64位，正负号1位，指数11位，精度52位 |
| complex64           | 复数，分别用两个32位浮点数表示实部和虚部          |
| complex128或complex | 复数，分别用两个64位浮点数表示实部和虚部          |

## 基础的数组运算

数组也可以进行我们常用的加减乘除运算

In [4]:
arr=np.array(np.arange(10))
print(arr*2)

[ 0  2  4  6  8 10 12 14 16 18]


In [5]:
arr1=np.array(np.arange(1,11))
print(arr)
print(arr1)
print(arr+arr1)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]


### 数组索引

In [6]:
arr=np.arange(10)
print(arr[5])

5


### 切片索引

In [7]:
print(arr[5:8])

[5 6 7]


可以利用索引对数据进行更改操作

In [8]:
arr[5]=120
print(arr)

[  0   1   2   3   4 120   6   7   8   9]


### 布尔操作

In [9]:
arr=np.arange(5)
name=np.array(['a','b','b','c','a'])
print(name=='a')

[ True False False False  True]


可以利用name数组设置条件后的布尔值对arr数组进行相关操作

In [10]:
print(arr[name=='a'])

[0 4]


### 多条件操作

In [11]:
result=(name=='a')|(name=='c')
print(result)
print(name[result])

[ True False False  True  True]
['a' 'c' 'a']


### 相关的函数方法使用

#### np.meshgrid 用于生成多维矩阵

In [12]:
a,b=np.meshgrid(np.arange(1,5),np.arange(2,5))
print(a)
print()
print(b)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


np.where 是三元表达式  x if  condition  else y的矢量化版本

In [13]:
arr1=np.arange(5)
arr2=np.arange(20,25)
condition=np.array([1,0,1,0,0]) 
result=np.where(condition,arr1,arr2)
print(arr1)
print(arr2)
print(result)

[0 1 2 3 4]
[20 21 22 23 24]
[ 0 21  2 23 24]


### 数学统计方法

在数组中我们也可以使用数学统计方法进行计数，例如sum mean  std  等

In [14]:
arr=np.random.randint(1,20,10)
print(arr)
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[ 6 11  6  9 13 12  1 17 18  5]
9.8
98
5.15363949069


### 布尔型数组的相关统计方法

In [15]:
arr=np.arange(-20,10)
result=(arr>5).sum()
print(arr)
print()
print(arr>5)
print()
print(result)

[-20 -19 -18 -17 -16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3
  -2  -1   0   1   2   3   4   5   6   7   8   9]

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True  True  True]

4


#### 线性函数的常用方法

In [16]:
arr=np.array([np.random.randint(1,10,5),np.random.randint(10,20,5)])
print(arr)
print(np.dot(arr,2))


[[ 5  4  6  6  3]
 [12 17 17 12 11]]
[[10  8 12 12  6]
 [24 34 34 24 22]]


#### 随机数生成方法

In [17]:
arr=np.random.random(10)
print(arr)

[ 0.79893773  0.40965751  0.83821298  0.95949433  0.20252982  0.75947237
  0.0198154   0.25163058  0.97925011  0.71490336]
